services:
  app:
    image: 'docker-rhlm-back:lastet'
    build:
      context: .
    container_name: app
    depends_on:
      - mysql
    ports:
      - "8080:8080"

  mysql:
    image: mysql  # Cambia a la versión que necesitas
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: RHLMGYM
      MYSQL_USER: carlitos
      MYSQL_PASSWORD: carlitos
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: